name: bud_get
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  auto_route: ^10.3.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  path: ^1.9.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2

dev_dependencies:
  auto_route_generator: ^10.2.6
  # lean_builder: ^0.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
